### ISSUE TITLE
Order is not confirmed

### ISSUE THREAD

**Issue by sluggogle** [fizcris/odoo_custom_addons#1]
First of all, it is nice to see that someone put an opensource cash on delivery module.
That's definitely something missing from Odoo by default.

I'm do not really understand the idea behind linking the delivery method and the payment acquire but that's not the issue here.

I think that the order should be confirmed automatically, which will trigger the delivery order. That should even create the invoice that will be given to the carrier.

I understand that not confirming the order let the user detects false positive before reserving stocks...

That's a good topic to discuss imo, and after all I wanted to give you 👍

**Comment by fizcris** [comment]
`I'm do not really understand the idea behind linking the delivery method and the payment acquire but that's not the issue here.`

It is especially useful to merge both during the checkout process so the customer can do both things (Select payment method and shipping method) just with a click. Bear in mind that this addon might not work if there are multiple shipping providers. It could be solved differently but for me, it was the simplest way to make it work.

`I understand that not confirming the order let the user detects false positive before reserving stocks...`

The order is not confirmed for a reason, for small businesses the consequences of scams are quite heavy, so many owners prefer to contact the buyer in advance via phone to have an order confirmed before reserving the items if they have not received the cash in advance, and then confirm the order later.

`I think that the order should be confirmed automatically, which will trigger the delivery order. That should even create the invoice that will be given to the carrier.`

I think you can achieve this easier with a planned action rather than with code...


`That's a good topic to discuss imo, and after all I wanted to give you 👍`
Cheers for that! Feel free to make a PR and if you want to include some improvements. 
If there are people interested in it I will try to keep it up to date as I found some minor bugs but I haven't updated this repo yet.
